# Generated by Django 6.0.1 on 2026-03-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_academic_year_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Birth Certificate Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='iqama_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Iqama / National ID Expiry Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_vaccinated',
            field=models.BooleanField(default=False, verbose_name='Vaccination Record Provided'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Medical Insurance Expiry Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_insurance_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Medical Insurance Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Passport Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Student Photo'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Previous School Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_certificate_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Transfer Certificate Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='vaccination_card_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vaccination Card Number'),
        ),
    ]
